### ISSUE TITLE
Git checking should look for .gitignore_global  file

### ISSUE THREAD

**Issue by deaddrop9** [b3nj5m1n/xdg-ninja#10]

**Comment by b3nj5m1n** [comment]
I'm not sure what you mean by this, unfortunately, could you elaborate a bit more?

**Comment by deaddrop9** [comment]
Sorry when i ran the tool, the file i mentioned above was left behind, figure it was standard config, on review the naming and location of the global gitignore is up to the user. 

Will close this out.
