### ISSUE TITLE
[Feature Request] Flatpak

### ISSUE THREAD

**Issue by Doomsdayrs** [b3nj5m1n/xdg-ninja#107]
Distribute via flatpak?

**Comment by garrhow** [comment]
I wrote a Flatpak manifest (plus appinfo and desktop entry). It builds quickly and works well in a desktop environment when using the launcher. It uses git tags to download xdg-ninja releases. It may be a bit messy so feel free to adapt this to your liking!

https://github.com/garrhow/com.github.b3nj5m1n.xdg-ninja

**Comment by b3nj5m1n** [comment]
I'll close this since a manifest now exists.
