### ISSUE TITLE
Glow pager mode break output

### ISSUE THREAD

**Issue by Tokariew** [b3nj5m1n/xdg-ninja#111]
If in settings glow is set to use pager mode, the output is scrambled… instruction or comments appear as separate "page" without clear indication about what .dotfile they are talking. and after closing all pages i can see the list of .dotfiles.
screnshot attached for clarifing…
<details>
  <summary>screenshots</summary>

![20220628T071225](https://user-images.githubusercontent.com/7306237/176097895-f22d002f-724d-4054-b3f0-bee55c9231c0.png)
![20220628T071354](https://user-images.githubusercontent.com/7306237/176098069-5b6962c8-c47f-478e-8bbd-08b97cf0ebe6.png)
![20220628T071232](https://user-images.githubusercontent.com/7306237/176097898-21509aef-74c7-4839-9bec-2ce17c42cfa3.png)
 
</details>

**Comment by b3nj5m1n** [comment]
This is quite unfortunate, thank you for making me aware of this.

15a31bdc113604418aaac95c6ed01159883f5127 should fix this, although it's a bit of a hacky fix since glow doesn't seem to support an option to explicitly disable the pager.

Please let me know if this works for you.

**Comment by Tokariew** [comment]
yes, it's fixed for me with this commit

**Comment by tkapias** [comment]
About the same issue.

I would prefer to have the pager but piping to less lose some colors, even with -R.

Is there a way to keep the output with glow's pager feature?
