### ISSUE TITLE
 Error: no lexer for alias 'markdown' found [Ubuntu based Linux mint xfce]

### ISSUE THREAD

**Issue by FallCheetah7373** [b3nj5m1n/xdg-ninja#115]
![image](https://user-images.githubusercontent.com/79195050/176167844-56eb6dd3-ba13-4822-aa9c-855b9c9c0e65.png)
I am not sure how do I go about fixing these issues...I tried installing glow but then xdg ninja didn't use it.

**Comment by hmoffatt** [comment]
I get this error on Debian 11 too.

**Comment by FallCheetah7373** [comment]
> This is a bit weird, are you able to run _glow_ normally?

Yes I had to compile glow. The only issue being I can only run it through ./glow on the compiled folder in home directory.

**Comment by b3nj5m1n** [comment]
You'll have to move the compiled binary to some directory on your _PATH_, like _/bin/_ or _/usr/bin/_.

**Comment by FallCheetah7373** [comment]
> You'll have to move the compiled binary to some directory on your _PATH_, like _/bin/_ or _/usr/bin/_.

that fixed it thanks!

**Comment by b3nj5m1n** [comment]
That means you haven't set the XDG environment variables.

If you want them all at their default location, this probably isn't a huge deal, as almost every program will use the default location as a fallback.

If you did want to set these, you could indeed do it in your _.bashrc_.

**Comment by hmoffatt** [comment]
I have the same error and I don't even have glow.

**Comment by FallCheetah7373** [comment]
> I have the same error and I don't even have glow.

https://github.com/charmbracelet/glow

**Comment by hmoffatt** [comment]
> https://github.com/charmbracelet/glow

Fine, but the console output says it will work without glow, but it doesn't:

```
Markdown rendering will be done by pygmentize. (Glow is recommended)
...
[android-studio]: $HOME/.android
Error: no lexer for alias 'markdown' found
```

**Comment by b3nj5m1n** [comment]
This is a problem with pygmentize, and since I'm not familiar with that tool, I unfortunately can't provide any assistance.

**Comment by hmoffatt** [comment]
OK it looks like it needs a newer version of pygments. I installed it from pip and now this runs.
