### ISSUE TITLE
python_history

### ISSUE THREAD

**Issue by DhruvaSambrani** [b3nj5m1n/xdg-ninja#13]
This can be a suggestion- 
https://unix.stackexchange.com/questions/630642/change-location-of-python-history

**Comment by b3nj5m1n** [comment]
This seems very complicated at first glance, I'll have to look at it later.

**Comment by b3nj5m1n** [comment]
Added in d6e4de0e68920c57779361f6983f884ef2e8d9e6.

**Comment by alichtman** [comment]
I think this solution is incomplete. `~/.python_history` is still created since the hook to write to `~/.python_history` isn't removed / disabled. I wrote a more complete solution in this answer (on the same post linked above): https://unix.stackexchange.com/a/747364/321263
