### ISSUE TITLE
Additional programs

### ISSUE THREAD

**Issue by pikeas** [b3nj5m1n/xdg-ninja#132]
Love the repo, thanks for being a fantastic resource!

Here are some additional files and directories not covered:

- `.conda`: https://www.anaconda.com/
- `.matplotlib`: https://matplotlib.org/
- `.terraform.d`: https://terraform.io/
- `.tool-versions`: http://asdf-vm.com/ 
- `.Trash`: MacOS Trash directory, described as "probably a custom directory", description can be more direct under MacOS.
- `.ts_node_repl_history`: https://github.com/TypeStrong/ts-node
- `.visidata`: https://www.visidata.org/

**Comment by b3nj5m1n** [comment]
Hi, thank you so much for making me aware of these!

Unfortunately, I won't be able to add all of these myself, for example there's already #14 about conda. It's a very complex program with very complex documentation, and even if I found the required settings, I'm not confident I'd be able to properly test if they break anything.

I'll take a look at the others when I get the time!

**Comment by b3nj5m1n** [comment]
- [ ] .conda (being tracked in #14)
- [x] .matplotlib (added with fa40915)
- [x] .terraform.d (added with fa40915)
- [x] .ts_node_repl_history (added with fa40915)
- [x] .visidata (added with #136)
- [ ] .tool-versions
- [ ] .Trash

## .tool-versions

It seems like this file is only created in the working directory, not in the home directory? At least that's how I interpret the docs, see [here](https://asdf-vm.com/manage/configuration.html#environment-variables) for the relevant section:

> ASDF_DEFAULT_TOOL_VERSIONS_FILENAME - The filename of the file storing the tool names and versions. Defaults to .tool-versions. Can be any valid filename. Typically you should not override the default value unless you know you want asdf to ignore .tool-versions files.

If I'm wrong about this please tell me and I'll a note about the enviornment variable.

## .Trash

I'm not a mac user and a quick search didn't yield any results, if you know for a fact that this is moveable feel free to open a new issue.
