### ISSUE TITLE
I changed XAUTHORITY env var , but this breaks mpv in video

### ISSUE THREAD

**Issue by soracqt** [b3nj5m1n/xdg-ninja#135]

**Comment by b3nj5m1n** [comment]
Hi, unfortunately, changing the XAUTHORITY variable is very dicey, and there's been numerous problems reported because of it. Are you using a compatible login manager and setting the variable in its configuration?

**Comment by soracqt** [comment]
i'm using startx
 im creating the issue assuming this doesn't work.
I'd be happy to help in any way I can.

**Comment by b3nj5m1n** [comment]
I don't have any experience using startx, unfortunately.

Could you confirm that the XAUTHORITY file is valid? You can do this by running `xauth -f "$XAUTHORITY"`, that should open a command prompt, type `list` and hit enter, that should produce information about the current session, something like this:
```
hostname/unix:  MIT-MAGIC-COOKIE-1  hash
```

**Comment by soracqt** [comment]
ok thank you!
i'll try this on tomorrow

**Comment by soracqt** [comment]
The settings on my end were wrong.
Sorry.
closing this issue , Thank you
