### ISSUE TITLE
.dotnet

### ISSUE THREAD

**Issue by DhruvaSambrani** [b3nj5m1n/xdg-ninja#15]
There is no configurable way, but there is an active issue here - https://github.com/dotnet/sdk/issues/8678

Until then, we cry.

**Comment by b3nj5m1n** [comment]
That's too bad. I haven't added a lot of configurations for files that cannot be moved, but I intend to add those in the near future with references to relevant issues. Thanks for reporting!

**Comment by b3nj5m1n** [comment]
Added this in 35a7b91a7a67596d4004eb76a718a055a6baf91a.

Let's hope they add support!
