### ISSUE TITLE
Additional Programs + Steam bypass

### ISSUE THREAD

**Issue by JustOptimize** [b3nj5m1n/xdg-ninja#163]
Hi, here are some additional files and directories that aren't covered:
- `.anydesk`: https://anydesk.com/en
- `.lunarclient`: https://www.lunarclient.com/
- `.selected_editor`: Generated by /usr/bin/select-editor
- `.sudo_as_admin_successful`: https://github.com/sudo-project/sudo/issues/56

For the steam files, the flatpack version doesn't create the files in the home dir (because flatpack creates it's own container) so it could be used to remove these

Loving this project, my home directory has never been this clean

**Comment by FranciscoPombal** [comment]
>     * `.selected_editor`: Generated by /usr/bin/select-editor

You're better of just using `VISUAL` and/or `EDITOR`, which override `SELECTED_EDITOR` and are more universal IMO. Also consider simply running `update-alternatives --config editor` if you're on Debian/Ubuntu or derivatives.

> * `.sudo_as_admin_successful`: [Remove .sudo_as_admin_successful file from home folder.  sudo-project/sudo#56](https://github.com/sudo-project/sudo/issues/56)

https://github.com/b3nj5m1n/xdg-ninja/pull/165.

**Comment by thokr** [comment]
Are there any known solutions for `.anydesk`? I think it can only be fixed by the company, since it's closed source. And their customer support seems to be behind a paywall. Maybe someone here happens to have a subscription and could contact them with a feature request?

**Comment by JustOptimize** [comment]
Should we change the steam thing to suggest using flatpack as a temporary solution?
It's less integrated with the system and has some little problems but at least it doesn't create those annoying files

**Comment by b3nj5m1n** [comment]
I'd be okay with adding a note at the bottom of the steam entry suggesting flatpack.

If you want to create a PR for this, go ahead. Otherwise, I can add it in a couple of days myself.
