### ISSUE TITLE
less history should be in $XDG_STATE_HOME, not CACHE_HOME

### ISSUE THREAD

**Issue by adinklotz** [b3nj5m1n/xdg-ninja#177]
When finding the default `.lesshst` in home, xdg-ninja currently suggests:
```
[less]: ${HOME}/.lesshst

  Export the following environment variables:

    export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
```

As discussed in #45 history files generally want to be in the new $XDG_STATE_HOME. I think less history similarly fits better as state than as cache, since it seems to clearly fit

> - actions history (logs, history, recently used files, …)
> - current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

Your `less` search history obviously doesn't matter as much as your shell history, but it can't be regenerated if lost, so I don't think can be considered cache either. I propose instead suggesting
```
    export LESSHISTFILE="$XDG_STATE_HOME"/less/history
```

**Comment by b3nj5m1n** [comment]
Fixed with ce8bf2c15c7cfca22b1911068fbe7d13a1108c9b.
