### ISSUE TITLE
Add support for XSANE

### ISSUE THREAD

**Issue by alsoGAMER** [b3nj5m1n/xdg-ninja#186]
~~https://wiki.archlinux.org/title/SANE~~

**Comment by b3nj5m1n** [comment]
Hi, unfortunately I couldn't find much information on this, and I'm unfamiliar with the project.

It would be helpful to know which files the program creates, and what the name of the actual program is that creates these files. I found the projects [gitlab page](https://gitlab.com/sane-project), but I'm not sure in which repository searching for or creating an issue about xdg would be appropriate.

**Comment by alsoGAMER** [comment]
Sorry, I opened the issue in a rush and didn't include anything useful.
The software creating the `.sane` folder is https://gitlab.com/sane-project/frontend/xsane.

Full path and contents: `.sane/xsane/xsane.rc`.
I also attached the rc file (as a zip, cause github), just in case you need it.
[xsane.rc.zip](https://github.com/b3nj5m1n/xdg-ninja/files/9943921/xsane.rc.zip)

**Comment by alsoGAMER** [comment]
It also appears that the software searches for the `SANE_DATA_DIR` env-var, if isn't set it'll fallback to `$HOME/.sane/xsane`, but I'm unable to test if setting that makes any difference because I'm unfamiliar as you with this project.

https://gitlab.com/sane-project/frontend/xsane/-/blob/master/xsane.CHANGES#L632

**Comment by b3nj5m1n** [comment]
Ok so this is a bit of a weird one, from the changelog it does indeed look like exporting that env var should work, I just tested it and well, it doesn't actually seem to do anything.

Note that you can use the alias `xsane --xsane-rc $XDG_CONFIG_DIR/sane/xsane/xsane.rc` to at least store your config file in `.config`, but it will still create an (empty) directory whenever you run the app.

I've added the info to xdg-ninja in 7024e08a90eaaccdae7a41a396569f0bb4d8d696 and created an [issue](https://gitlab.com/sane-project/frontend/xsane/-/issues/55) regarding this.

**Comment by alsoGAMER** [comment]
> Ok so this is a bit of a weird one, from the changelog it does indeed look like exporting that env var should work, I just tested it and well, it doesn't actually seem to do anything.

As I suspected, sadly.

> Note that you can use the alias `xsane --xsane-rc $XDG_CONFIG_DIR/sane/xsane/xsane.rc` to at least store your config file in `.config`, but it will still create an (empty) directory whenever you run the app.

I don't run it via cmdline, but I'll set that anyway.
> I've added the info to xdg-ninja in [7024e08](https://github.com/b3nj5m1n/xdg-ninja/commit/7024e08a90eaaccdae7a41a396569f0bb4d8d696) and created an [issue](https://gitlab.com/sane-project/frontend/xsane/-/issues/55) regarding this.

Thank you for your time!
