### ISSUE TITLE
.trash on mac

### ISSUE THREAD

**Issue by realitymolder** [b3nj5m1n/xdg-ninja#202]
Partly bug / partly question(?)
Don't crucify me, at the moment the output of .trash is:

```
  This is probably a custom directory on your system.
  You can move the file to XDG_DATA_HOME/trash.
```
My question is: If that is also relevant to macOS, or is it Linux only? If it's Linux only, it needs to be fixed.
On macOS, the .trash folder is the user's system-trash folder.

Thanks

**Comment by b3nj5m1n** [comment]
If I understand correctly, you can't move the directory to XDG_DATA_HOME on macOS?

If that's the case, there should definitely be a note about this in the output.

**Comment by yochem** [comment]
I'm not 100% sure, but I couldn't find any documentation on how to move the folder. As it's treated as a special folder under MacOS, I think it can not be moved.

**Comment by b3nj5m1n** [comment]
Thank you, I've added a note in cda9beb, **if someone finds a way to move this directory, please open a PR or let me know**!

**Comment by realitymolder** [comment]
Good job. I think that will be it for now. If anybody will find a solution in the future (if there is any) we will update it.

**Comment by LuckyWindsck** [comment]
I am a macOS user, and it seems like it's still unmovable now.

However, every time I run `$ xdg-ninja --skip-unsupported`, the information of `.trash` will be shown, and the EXIT CODE (= The number of FIXABLE program) will be at least 1.

<img width="1580" alt="Image" src="https://github.com/user-attachments/assets/705232e9-836d-45bc-a601-e389eb610c49" />

Is there any recommendation of how to skip the checking of `.trash` on macOS?

The following might be a possible workaround, but then I need to maintain my own version of `xdg-ninja` and keep update it periodically:

- Use the custom `$XN_PROGRAMS_DIR` environment variable, and then either overwrite the `"movable"` field of `.trash` from `true` to `false` or just delete `programs/trash.json`.
