### ISSUE TITLE
~/.zshenv can export ZDOTDIR or point somewhere else, a check should be necessary

### ISSUE THREAD

**Issue by formula-spectre** [b3nj5m1n/xdg-ninja#206]
apologies for bad title  
basically I use home-manager and my ~/.zshenv only contains this:
```source $HOME/.config/zsh.nix/.zshenv```  
because it was generated by home-manager. on my older setup my ~/.zshenv used to contain only ```export ZDOTDIR=${XDG_CONFIG_HOME}/zsh```  
I think a check should be made for these cases?

**Comment by b3nj5m1n** [comment]
Hi, unfortunately, checking for edge cases like these would be way too complex to implement and maintain, sorry.
