### ISSUE TITLE
Using pam_environment

### ISSUE THREAD

**Issue by NoelJacob** [b3nj5m1n/xdg-ninja#21]
Another kind of clutter is so much .profile .bashrc .bash_profile etc variables and not being able to switch shells easily. Adding environment variables to system pam env and home pam env reduces this clutter.
I've been using .pam_environment instead of .shellrcs for while but the devs want to discontinue it and depreciated it.
Edit: ~/.config/environment.d/*.conf for local variables and /etc/environment for system variables are good alternatives. ~/.config/env is loaded by systemd so don't know if few non-systemd systems support this.

**Comment by b3nj5m1n** [comment]
Tbh I think it's fine as is, since you only have to set the variables in the shell config file that you already have anyway.
