### ISSUE TITLE
Unable to parse list markdowns

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [b3nj5m1n/xdg-ninja#211]
Running `xdgnj prev` on the following config file gave an error.
```
{
   "name":"anacondaAUR",
   "files":[
      {
         "path":"~/.conda/.condarc",
         "movable":true,
         "help":"pkgs_dirs:\n  - ${XDG_CACHE_HOME}/conda/pkgs\n"
      }
   ]
}
```

`xdgnj: /tmp/xdg-ninja.6817cde6-410a-4526-ba99-beab8e5f2e91.txt: hGetContents: invalid argument (invalid byte sequence)`

```
> cat /tmp/xdg-ninja.795d8231-1933-48bc-8119-aa217a7ca776.txt

  • ${XDG_CACHE_HOME}/conda/pkgs
```

My guess is the binary is unable to parse this `•` symbol.

**Comment by b3nj5m1n** [comment]
Sorry, but I'm unable to reproduce this issue. `xdgnj prev` runs fine on the file.

Are you using the most recent release binary of xdgnj?

**Comment by ShivanshuKantPrasad** [comment]
Unfortunately the solution provided in the original thread didn't work on my pc. For anyone else facing the same issue, I started a thread on NixOS discourse [here.](https://discourse.nixos.org/t/how-to-set-locale-archive-environment-variable-properly-on-nixos/24598).
