### ISSUE TITLE
Scrap XDG Base Directory article on Archwiki

### ISSUE THREAD

**Issue by ShivanshuKantPrasad** [b3nj5m1n/xdg-ninja#212]
I wrote a simple nodejs script that scraps [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory) article on Archwiki and creates config files that are compatible for xdg-ninja tool. 

Script Repo: https://github.com/ShivanshuKantPrasad/xdg-ninja-config-generator

**Comment by b3nj5m1n** [comment]
This is very cool, but it seems like it'll be quite a bit of work to clean those files up and merge them, I'll start working on it on a separate branch.

**Comment by b3nj5m1n** [comment]
You can find the branch [here](https://github.com/b3nj5m1n/xdg-ninja/tree/arch_wiki_scrape).

I think I removed most of the duplicates.

All the files that have to be cleaned up and moved over to `programs/` are in the `generated_configs/` directory.

**Comment by ShivanshuKantPrasad** [comment]
I noticed some entries on archwiki do not have any path. Such entries are useless for xdg-ninja. So I updated the script to ignore any entry without any paths.

List of all ignored files: https://gist.github.com/ShivanshuKantPrasad/0a676d7e1422251f269d86a43d2c8089

**Comment by b3nj5m1n** [comment]
Thanks, removed those in dbcca96727d4d68ad92458e87b699fbef38795d8.

**Comment by flexagoon** [comment]
Hey @b3nj5m1n are you still planning to tackle this? If your branch is stale, perhaps I can work on this

**Comment by b3nj5m1n** [comment]
> Hey @b3nj5m1n are you still planning to tackle this? If your branch is stale, perhaps I can work on this

@flexagoon If you want to work on this, I'd be very grateful. But be warned, manually going through and removing duplicates and manually cleaning up the configs was some of the most boring work I've ever done, and I feel like I've barely made any progress.
