### ISSUE TITLE
gitconfig

### ISSUE THREAD

**Issue by mxmlnkn** [b3nj5m1n/xdg-ninja#232]
#2 mentions it but the linked commit did not add support for `~/.gitconfig`. As per the `antidot/rules.yaml`, it should simply be moved to `${XDG_CONFIG_HOME}/git/config`. See also [git-config](https://git-scm.com/docs/git-config):

> For writing options: write to global `~/.gitconfig` file rather than the repository `.git/config`, write to `$XDG_CONFIG_HOME/git/config` file if this file exists and the `~/.gitconfig` file doesn’t.
>
> For reading options: read only from global `~/.gitconfig` and from `$XDG_CONFIG_HOME/git/config` rather than from all available files.

So, yes, simply moving it should suffice.

**Comment by b3nj5m1n** [comment]
`~/.gitconfig` should have been added with 6bdc0881, and it's in the file for git: https://github.com/b3nj5m1n/xdg-ninja/blob/4ee47996cb48f51a2a52d64bc5cb0e8967522e59/programs/git.json#L5-L7.

Are you not seeing it in the output when running xdg-ninja?

**Comment by mxmlnkn** [comment]
My bad. There is output, it was just so short compared to the others that I did not see it. In general, I find the formatting rather chaotic. Maybe an empty line before each new tool would help or by indenting the instructions or by first giving a oneline hint what is supported and what not and only then the full instructions for each tool. Also, why are the colors different? Some tools are yellow some red and the red ones are supported, it seems. Personally, I would have expected them to be green. The yellow ones are unsupported it seems, I would have expected them to be red. Maybe use yellow for some not well-supported like those requiring the export of an environment variable.
