### ISSUE TITLE
.skiko note

### ISSUE THREAD

**Issue by zt64** [b3nj5m1n/xdg-ninja#237]
Hi,

`.skiko` is another folder created in the users home directory. Currently there isn't no way to override this, as it's [hardcoded](https://github.com/JetBrains/skiko/blob/e825dd01ef9da8d8469444f06c0e4e526d428339/skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt#L11). And it is an issue on the JetBrains YouTrack: https://youtrack.jetbrains.com/issue/FL-10572. 

Maybe this could be added, but labelled as not possible for the time being?

**Comment by e-khurmamatov** [comment]
> Maybe this could be added, but labelled as not possible for the time being?

Created pull request based on your description (see #262).

**Comment by zt64** [comment]
> > Maybe this could be added, but labelled as not possible for the time being?
> 
> @zt64 created pull request based on your description (see #262).

Oh they added a way to change it? Neat
