### ISSUE TITLE
Why recommend hardcoding XDG vars to the default values ?

### ISSUE THREAD

**Issue by cvlc12** [b3nj5m1n/xdg-ninja#255]
Hi !

Thanks for this very nice tool which I discovered today. 

I'm confused about the recommendation to hardcode default the XDG vars though, to my knowledge, these variables are meant to be set to **change** the defaults. There is no point in setting `XDG_CONFIG_HOME=$HOME/.config` as it already is the fallback default, if the spec is followed (and if it's not, then what's the point ?)

So if I understand correctly, it looks like the recommendations below are somewhat contrary to the specification 

```
The $XDG_DATA_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.local/share
The $XDG_CONFIG_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.config
The $XDG_STATE_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.local/state
The $XDG_CACHE_HOME environment variable is not set, make sure to add it to your shell's configuration before setting any of the other environment variables!
    ⤷ The recommended value is: $HOME/.cache
```

see also https://github.com/systemd/systemd/issues/20427#issuecomment-897400520

**Comment by b3nj5m1n** [comment]
A lot of the programs I'm aware of need these variables set.

**Comment by itaranto** [comment]
I don't think this is entirely correct, as it recommends a setting that will make detecting misbehaving applications harder.

Applications that follow the spec *should not* require the variables to be defined, they should use the default values like `~/.cache`, `~/.config`, etc.

**Comment by itaranto** [comment]
It can also misled users to think the `XDG_` variables are required for the spec to work when they are not.

**Comment by lgarron** [comment]
> A lot of the programs I'm aware of need these variables set.

For what it's worth, I've run into this a bunch of times — programs that honor the env vars but not the defaults. Some of them fix that over time, but there's always a chance you're using programs that don't. For those of us for who want to minimize the amount of gardening to keep their home dir clean, setting the env vars definitely has value. As much as I agree this *should* definitely not be necessary.

**Comment by itaranto** [comment]
> > A lot of the programs I'm aware of need these variables set.
> 
> For what it's worth, I've run into this a bunch of times — programs that honor the env vars but not the defaults. Some of them fix that over time, but there's always a chance you're using programs that don't. For those of us for who want to minimize the amount of gardening to keep their home dir clean, setting the env vars definitely has value. As much as I agree this _should_ definitely not be necessary.

But that prevents from actually finding about those issues and reporting them.

If an application requires the `XDG_*` variables to be XDG compliant then that should be in the workaround reported by xdg-ninja IMHO.

**Comment by lgarron** [comment]
> > > A lot of the programs I'm aware of need these variables set.
> > 
> > 
> > For what it's worth, I've run into this a bunch of times — programs that honor the env vars but not the defaults. Some of them fix that over time, but there's always a chance you're using programs that don't. For those of us for who want to minimize the amount of gardening to keep their home dir clean, setting the env vars definitely has value. As much as I agree this _should_ definitely not be necessary.
> 
> But that prevents from actually finding about those issues and reporting them.
> 
> If an application requires the `XDG_*` variables to be XDG compliant then that should be in the workaround reported by xdg-ninja IMHO.

I mean, I agree about the value of finding issues and reporting them. But that is value to the *community*, rather than value to the user who just wants as many programs as possible to avoid writing directly into the home dir.
