### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by grushaas** [b3nj5m1n/xdg-ninja#268]
Hi, I'm sorry for the stupid question for you, but I've never used the nix command. I can't figure out how to install this project. Do I need to make a clone of the repository and then run the command in the root of the project? Or how?

**Comment by b3nj5m1n** [comment]
You don't need to use nix: https://github.com/b3nj5m1n/xdg-ninja#cloning-manually

Basically:
```bash
git clone https://github.com/b3nj5m1n/xdg-ninja.git
cd xdg-ninja
./xdg-ninja.sh
```
