### ISSUE TITLE
Moving .xinitrc is not warned to be potentially dangerous

### ISSUE THREAD

**Issue by ArcWandx** [b3nj5m1n/xdg-ninja#274]
The xinitrc should come with a warning that your window manager/desktop environment may not start if you move it. For me personally (BSPWM on Arch Linux), I use `startx`, which specifically looks for `$HOME/.xinitrc`. Note that in this situation, `startx` would have to be modified to look for `$HOME/.config/X11/xinitrc`, unless `$XDG_CONFIG_HOME` can be set before startx is called (This can be done by setting the XDG HOME variables in `.bash_profile` (or `.zprofile` for me). Most people probably use `.bashrc` for setting the variables though).

**Comment by vickyorlo** [comment]
Moving Xauthority can break your DM as well, as I have found. My KDE Xorg session would not start (wayland was fine), and running Wine via a terminal would break with a "screen not found"- type error. Turns out it was because of the Xauthority/.xinitrc exports I added as recommended by xdg-ninja.
