### ISSUE TITLE
.android, .expo, .bubblewrap

### ISSUE THREAD

**Issue by Pika-Pool** [b3nj5m1n/xdg-ninja#32]
There is no configuration for `.android`, which can be set using `ANDROID_USER_HOME`: https://developer.android.com/studio/command-line/variables

`.expo` is used by the [expo-cli](https://expo.dev/), which is An open-source platform for making universal native apps with React. Expo runs on Android, iOS, and the web.

`.bubblewrap` is used by [bubblewrap-cli](https://github.com/GoogleChromeLabs/bubblewrap), which helps developers to create a Project for an Android application that launches an existing Progressive Web App (PWAs) using a Trusted Web Activity.

**Comment by b3nj5m1n** [comment]
> There is no configuration for .android, which can be set using ANDROID_USER_HOME

This confuses me a bit, I'm assuming it's a typo. I've added a configuration saying that you should set _ANDROID_USER_HOME_ to _XDG_DATA_HOME/android_, please try it out and let me know if this works.

---

I couldn't find anything on expo, unfortunately. I've added it as unsupported. If you know of a way to change the behaviour, or know of a relevant issue, please let me know.

---

Bubblewrap seems to be unsupported, I found this issue https://github.com/GoogleChromeLabs/bubblewrap/issues/362, if you can set the config path using environment vars or an alias, please let me know.

---

See debb51a88ad50c2018407d255dea649f31265bb9
