### ISSUE TITLE
Solution for Hammerspoon on MacOS - Could someone please add to XDG-Ninja ?

### ISSUE THREAD

**Issue by andrewcrook** [b3nj5m1n/xdg-ninja#331]
Could someone please add to XDG-Ninja these instructions for .hammerspoon ?

1. Quit Hammerspoon

2. from command line 
move/rename  `.hammerspoon` to `$HOME/.config/hammerspoon`

3. then on the command line use 
`defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua”`

4. restart hammerspoon

**Comment by flexagoon** [comment]
This already exists

https://github.com/b3nj5m1n/xdg-ninja/blob/main/programs/hammerspoon.json

**Comment by andrewcrook** [comment]
Not sure why I wasn’t seeing this but it is indeed in the db
