### ISSUE TITLE
[Feature Request] Lint mode?

### ISSUE THREAD

**Issue by ari-becker** [b3nj5m1n/xdg-ninja#351]
I'm thinking of writing a cron script to run `xdg-ninja` on a regular basis and notify me if it finds any violations. In this way, I don't have to remember to run `xdg-ninja` on a regular basis, and new violations are found closer/earlier to when a program violates them.

At the moment, however, the output of `xdg-ninja` can't be configured: it will always include files like `$HOME/.bashrc` that can't be moved (at least for now), and the exit code is always 0.

Could `xdg-ninja` support some kind of linting mode?

**Comment by flexagoon** [comment]
Xdg-ninja has a `--skip-unsupported` flag

**Comment by ari-becker** [comment]
@flexagoon I have it installed via homebrew.
Maybe this is really a request to update the homebrew release then?

![image](https://github.com/b3nj5m1n/xdg-ninja/assets/1388505/04d6b0f9-f143-40f7-a0af-ade3c61dd9b7)

**Comment by flexagoon** [comment]
@ari-becker the Homebrew package is built from tagged versions of xdg-ninja, the last of which is from 2022:

https://github.com/b3nj5m1n/xdg-ninja/releases

You should install the git version of xdg-ninja using `brew install xdg-ninja --HEAD` to get the latest version

**Comment by ari-becker** [comment]
> @ari-becker the Homebrew package is built from tagged versions of xdg-ninja, the last of which is from 2022:
> 
> https://github.com/b3nj5m1n/xdg-ninja/releases
> 
> You should install the git version of xdg-ninja using `brew install xdg-ninja --HEAD` to get the latest version

Nice, the latest version is what I wanted.

@flexagoon @b3nj5m1n could you tag a new release for Homebrew users? Or change the docs to recommend using `--HEAD` instead?

I'll close since my usecase is fit by the latest version (well, nearly, since `~/.trash` isn't excluded as unsupported on macOS, but this is already open in https://github.com/b3nj5m1n/xdg-ninja/issues/287 ).

**Comment by flexagoon** [comment]
> could you tag a new release for Homebrew users? Or change the docs to recommend using --HEAD instead?

I'm not the developer of this project, so I can't do that. There is an issue about this at #204, you should probably comment there
