### ISSUE TITLE
[BUG] xdg-ninja says to move ~/.fonts.conf to $XDG_DATA_HOME instead of $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by KAGEYAM4** [b3nj5m1n/xdg-ninja#388]
https://github.com/b3nj5m1n/xdg-ninja/pull/218,  says that it should be $XDG_CONFIG_HOME.

Also please look at this ->

xdg-ninja output regarding ~/.fonts directory
```
<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
 <dir>~/.fonts</dir>
</fontconfig>
```

~/.fonts.conf
```
<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
 <dir>~/.fonts</dir>
</fontconfig>
```

so after moving both, .conf needs to be edited? If yes, then a note indicating that would be nice.

**Comment by baschi29** [comment]
You seem to be right, see https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/8c255fb

[Arch wiki](https://wiki.archlinux.org/title/XDG_Base_Directory#Supported) also states

> Config goes in XDG_CONFIG_HOME/fontconfig/fonts.conf, fonts are stored in XDG_DATA_HOME/fonts/

Regarding editing .conf according to [the manpage](https://man.archlinux.org/man/fonts-conf.5#&lt;DIR_PREFIX=_DEFAULT&quot;_SALT=&quot;&quot;&gt;&quot;)  I guess one should change the directory to 
`<dir prefix="xdg">fonts</dir>`.
