### ISSUE TITLE
How should unsupported programs be handled?

### ISSUE THREAD

**Issue by Vikingat-RAGE** [b3nj5m1n/xdg-ninja#39]
As the title states how should unsupported programs be handled? Create an individual program.json file for it? Or have 1 and add to it?

**Comment by b3nj5m1n** [comment]
Create a file for that program, that way, you at least know which program created the file, since that is not always clear.

Create a files array as usual, but leave the help section as an empty string. (and set movable to false, obviously)

**Comment by b3nj5m1n** [comment]
Since 78d39de68357c9cdf0703f5c5a63888381c71f0f, add-program has a template for this.
