### ISSUE TITLE
Update swifttmp

### ISSUE THREAD

**Issue by vanyauhalin** [b3nj5m1n/xdg-ninja#399]
[Solution is here](https://github.com/apple/swift-package-manager/issues/6204/#issuecomment-1975505742)
[swift-package-manager.json](https://github.com/b3nj5m1n/xdg-ninja/blob/e9a16d1d90c5c2220b9c187b489b87f2190cac26/programs/swift-package-manager.json/)

**Comment by KaBankz** [comment]
The solution hasn't shipped yet, it will be part of Swift 6, which will be released somewhere after WWDC '24.

Since we are many months away, I suggest postponing updating the entry until it actually releases.
