### ISSUE TITLE
.pki

### ISSUE THREAD

**Issue by MathieuMoalic** [b3nj5m1n/xdg-ninja#43]
From this https://bbs.archlinux.org/viewtopic.php?id=265634](thread) it seems that the `.pki` folder can be moved to `$XDG_DATA_HOME/pki` if `$XDG_DATA_HOME` is set obviously. I have not tested this.

**Comment by b3nj5m1n** [comment]
Thank you, added a config in 3226b15c32cf4aa9f4491ed6b949e9100b2c80dc.
