### ISSUE TITLE
Should shell history files be STATE, CACHE, or DATA?

### ISSUE THREAD

**Issue by rocode** [b3nj5m1n/xdg-ninja#45]
For zsh/bash history files, currently:

[ArchWiki](https://wiki.archlinux.org/title/XDG_Base_Directory) suggests **STATE**.

[antidot](https://github.com/doron-cohen/antidot/blob/23cda210c9dbd18b7be3498d7a351b47f884b1aa/rules.yaml#L115) suggests **CACHE**.

xdg_ninja suggests **CACHE** for [bash](https://github.com/b3nj5m1n/xdg-ninja/blob/e05e0765bb5701d1bf772d4380c647d0ac92db1d/programs/bash.json#L7) and **DATA** for [zsh](https://github.com/b3nj5m1n/xdg-ninja/blob/e05e0765bb5701d1bf772d4380c647d0ac92db1d/programs/zsh.json#L16).

The XDG Base Directory Specification states:

>  The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
>
>   actions history (logs, history, recently used files, …)
>
>    current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

So I am leaning toward **STATE**, but figured I would ask first. :)

**Comment by b3nj5m1n** [comment]
Personally, I think shell history is important enough to be kept in the DATA dir.

There's several projects with thousands of stars that save more info about your history, adds an easier search mechanism, syncs it between machines, etc., so I think I'm not alone on this.

I'd say we stick with it for zsh, and change it to DATA for bash. Let me know your opinion, since I don't want to base this on just on my own opinion.

**Comment by rocode** [comment]
> Personally, I think shell history is important enough to be kept in the DATA dir.
> 
> There's several projects with thousands of stars that save more info about your history, adds an easier search mechanism, syncs it between machines, etc., so I think I'm not alone on this.
> 
> I'd say we stick with it for zsh, and change it to DATA for bash. Let me know your opinion, since I don't want to base this on just on my own opinion.

It's a tough call. XDG_STATE_HOME was only recently introduced, with the first proposal being in [December of 2016](https://lists.freedesktop.org/archives/xdg/2016-December/013803.html) and implementation into the specification in [May of  2021](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

I **believe** the rule of thumb is that state is machine-specific, while data is cross-machine. Since shell history is most commonly used to build completion rules/suggestions, you wouldn't want it transferred to other machines with a different context, or worse, leak sensitive data.

I am going to propose standardizing on STATE, since it appears to be the current specifications standard for history files, and seems to follow with the initial proposal.

Looking forward to any other thoughts or opinions before settling one way or another. :)
