### ISSUE TITLE
Feature request: dump results to a text file

### ISSUE THREAD

**Issue by mdebusk** [b3nj5m1n/xdg-ninja#73]
I'd love to see a command-line option to show the results in plain text, i.e., no color control codes or markdown, so I could redirect it to a text file.

**Comment by b3nj5m1n** [comment]
Hi, unfortunately, the configuration files use markdown, so you'd need some tool to convert the markdown to plain text, since I don't want to add another dependency I don't think I'll be able to address this issue, sorry.

**Comment by aflyingpumpkin** [comment]
I'd just like to say that it would be best to use `if [ -t 1 ]`, as well as a flag to bypass this.

**Comment by b3nj5m1n** [comment]
I'll close this since doing it properly would require an additional dependency and the interest in this feature isn't big enough to justify that.

Anybody who needs this should be able to just pass the output through something like pandoc: `pandoc --from markdown --to plain`.
