### ISSUE TITLE
isn't the description a bit misleading?

### ISSUE THREAD

**Issue by wael444** [b3nj5m1n/xdg-ninja#74]
> A shell script which checks your $HOME for unwanted files and directories. 

doesn't the program need Haskell?
why not write the program entirely in POSIX sh/bash?

**Comment by wael444** [comment]
the haskell and cabal programs are for getting the json files?

**Comment by b3nj5m1n** [comment]
The haskell program is just in case you want to add your own configuration or edit an existing one. You also just do this in your text editor, but it's less nice to edit json directly.
