### ISSUE TITLE
.help json value request

### ISSUE THREAD

**Issue by wael444** [b3nj5m1n/xdg-ninja#76]
for example:
```json
{
    "name": "bash",
    "files": [
        {
            "path": "${HOME}/.bash_history",
            "movable": true,
            "help": "Export the following environment variables:\n\n```bash\nexport HISTFILE=\"${XDG_STATE_HOME}\"/bash/history\n```\n"
        }
    ]
}
```
currently, i am trying to compeletely declutter and optimize xdg-ninja.
**please close this issue immediately if you do not agree with me.**

i request to simply change the json files to have markdown rendering removed. so the output could be something along the lines of:
```
Export the following environment variables:
$ export HISTFILE=\"${XDG_STATE_HOME}\"/bash/history
```
instead of a very colorful and in my opinion, bloated output.
most programs follow the 'standard' i had said above and doing this could actually save me some time trying to optimize xdg-ninja.

**Comment by wael444** [comment]
i can't really optimize xdg-ninja without a clear understanding of `apply_shell_expansion()` and `decode_string()`, i thought doing something like this wouldn't be so hard. but so far i've reached 80 SLOC

**Comment by b3nj5m1n** [comment]
Sorry, but I won't remove the markdown.

What exactly are you trying to optimise?

**Comment by wael444** [comment]
> Sorry, but I won't remove the markdown.

Okay. i guess i will try to add it in my optimized version.

> What exactly are you trying to optimise?

Everything. There is many duplicate lines and ton's of complicated scripting that could have been so simple, i can show you how it looks so far but it doesn't work as i completely removed the markdown rendering as that could make the script much more simpler and easier to manage.

**Comment by b3nj5m1n** [comment]
`apply_shell_expansion` expands environment variables in strings,`decode_string` does what the comment says: Replace \n with literal newline and \" with ", normalize number of trailing newlines to 2.

**Comment by wael444** [comment]
> expands environment variables in strings

Example?

**Comment by b3nj5m1n** [comment]
```
➜ apply_shell_expansion "\$XDG_CONFIG_HOME"
 /home/b3nj4m1n/.config
```

**Comment by wael444** [comment]
Hmm. Okay. i will soon open a PR and explain each change i did.
