### ISSUE TITLE
.steampid is missing

### ISSUE THREAD

**Issue by wael444** [b3nj5m1n/xdg-ninja#78]
`.steampid -> /home/wael/.steam/steam.pid`

i should have told you to add this in #75, but at that time i wasn't using steam.

**Comment by b3nj5m1n** [comment]
I'm not sure what you mean by this, it recognises .steampid and outputs no help available.

What exactly is your problem with this?

**Comment by wael444** [comment]
yeah, it gets reported, i didn't see it.
