### ISSUE TITLE
List of missing programs

### ISSUE THREAD

**Issue by a2n-s** [b3nj5m1n/xdg-ninja#80]
I really love that application :star_struck: 
I was able to quickly clean a lot of my `$HOME` directory and my dotfiles repo, really cool stuff we have here :+1: 

I wanted to further clean my `$HOME` and noticed, and that's normal considering the number of existing applications, a lot of hidden files and directories still hanging around without explicit permissions :thinking: 

Below are lists of all the directories and files I still have in my `$HOME`, I only removed those already supported by `xdg-ninja` but without definitive solution and my personal files. There might be items not relevant to `xdg-ninja`, please tell me and i'll remove them :wink:

If you prefer to split this issue into more little ones, this one can be closed and the job can be done.

I just thought a somewhat ""complete"" list of missing programs would be usefull :yum: 
And I would be more than happy to help if you accept external contributions :yum: 

**Missing directories:**
```
.arduino-create/
.arduino15/
.dwarffortress/
.eendroroy-coloschemes/
.emacs.d/
.gsutil/
.ipython/
.keras/
.kube/
.links/
.lyrics/
.moc/
.mujoco/
.oh-my-bash/
.oh-my-xonsh/
.pytest_cache/
.quickemu/
.screenlayout/
.slime/
.SpaceVim/
.SpaceVim.d/
.surf/
.telegram-cli/
.themes/
.thumbnails/
.trash/
.vim/ -> ~/.SpaceVim/
.vim_back/
.virtualbox/
.when/
.xmonad/
.zotero/
```

**Missing files:**
```
.bash_aliases
.bash_logout
.bash_profile
.bashrc
.bashrc.backup
.boto
.ctags
.dmrc
.gcalcli_cache
.gcalcli_oauth
.gnuplot_history
.grip-oggenc
.luahistory
.matho_history
.net.log
.notion-enhancer
.nwinkler_random_colors
.osh-update
.pdbhistory
.profile
.pulse-cookie
.python_history-83827.tmp
.rtorrent.rc
.sc_history
.sdirs
.viminfo
.vimrc_back
.xonshrc
.xscreensaver
.yarnrc
.zcompdump*
.zsh_history
```
**Special cases**:
- `gnupg`: this program is supported but the `~/.gnupg` file gets regenerated each time on my machine. This would be great to have a mention to that problem in the output of `xdg-ninja`

**Comment by a2n-s** [comment]
I removed `~/.steampid` as it is mentionned in #78.

**Comment by wael444** [comment]
thunderbird is added in https://github.com/b3nj5m1n/xdg-ninja/commit/05cec29037f19eb5b1cafc3a85a24599fb6c39f0

also thank you for pointing a lot of these out.

**Comment by a2n-s** [comment]
yes you're right I did not `git fetch` the new version, removing that :ok_hand:

**Comment by a2n-s** [comment]
so would you be open to PRs @wael444? :yum: 
just to know if it is worth working on some of the programs above :wink:

**Comment by wael444** [comment]
> just to know if it is worth working on some of the programs above wink

certainly maybe, 
all you need is a description on how to fix it, if it is movable and if it is fixable whatever.
I'm pretty sure you can use the XDG Base Directory wiki page on arch wiki for the resources as that's all i know of.
there are simply too many programs to be honest.
please add my issue #78 aka ~/.steampid to your issue.

**Comment by b3nj5m1n** [comment]
Hi @a2n-s, thank you so much, this is the most comprehensive list of missing applications I've got so far.

I originally intended to add unsupported apps from the xdg-base-dir page from the arch wiki, but it was not a high priority, so I haven't got around to it yet.

If you would be willing to make a PR for this, that would be awesome. It obviously doesn't have to be all of them, and if you want to do some now and some later, multiple PRs are more than welcome as well.

If you have cabal installed, you can compile the haskell program in this repository, that will make it easier to add new configurations. `cabal run xdgnj add` will guide you through the process of adding new configurations, you can preview the config for a program with `cabal run xdgnj prev programs/PROGRAM.json` (where PROGRAM is the name of the program you want to preview), and you can edit existing configurations with `cabal run xdgnj edit programs/PROGRAM.json`.

If you don't want to go through the trouble, it would still be very helpful if you were to compile the information necessary (I suspect in this case most of the files sadly won't be movable, so this necessary information would be the name of the program responsible for the creation of the file/dir, and optionally a link to a relevant issue discussing xdg compliance) and send that over to me, as a comment to this issue would be fine, then I would go through it myself and create the configs.

Either way, thank you so much for this report and the kind words!

**Comment by a2n-s** [comment]
> please add my issue #78 aka ~/.steampid to your issue.

I purposely removed `~/.steamip` from the list above as you mention it already in #78.

The goal of my issue is to shed light on missing programs in `xdg-ninja`, i.e. programs not in the code base, nor in any issue or PR, not to swallow the other issues into mine :yum:

**Comment by a2n-s** [comment]
> Hi @a2n-s, thank you so much, this is the most comprehensive list of missing applications I've got so far.
>
Hi @b3nj5m1n! :wave:
I think that is normal and the very minimum to make the life of maintainers of open-source projects easier with clear discussions :yum:
I'm far from perfect at that, but I simply try my best :wink:

> I originally intended to add unsupported apps from the xdg-base-dir page from the arch wiki, but it was not a high priority, so I haven't got around to it yet.
>
Oh I see, this is a great piece of information for the endeavour of `xdg-ninja`!

> If you would be willing to make a PR for this, that would be awesome. It obviously doesn't have to be all of them, and if you want to do some now and some later, multiple PRs are more than welcome as well.
>
I sure can do that, as stated in the opening message of the issue.

> If you have cabal installed, you can compile the haskell program in this repository, that will make it easier to add new configurations. `cabal run xdgnj add` will guide you through the process of adding new configurations, you can preview the config for a program with `cabal run xdgnj prev programs/PROGRAM.json` (where PROGRAM is the name of the program you want to preview), and you can edit existing configurations with `cabal run xdgnj edit programs/PROGRAM.json`.
>
> If you don't want to go through the trouble, it would still be very helpful if you were to compile the information necessary (I suspect in this case most of the files sadly won't be movable, so this necessary information would be the name of the program responsible for the creation of the file/dir, and optionally a link to a relevant issue discussing xdg compliance) and send that over to me, as a comment to this issue would be fine, then I would go through it myself and create the configs.
>
Do not worry, I'll try to find my way through `cabal` and the tools you propose to generate proper `.json` files :ok_hand:

> Either way, thank you so much for this report and the kind words!
>
Well, I was not that much aware of the mess my `$HOME` directory was... I knew it was filled with some hidden files, but time did pass and now it is quite out of control. I discovered your project with [this video from "The Linux Cast"](https://www.youtube.com/watch?v=XRnZavaEpvg) and, yeah, I do not want uncontrolled files in my `$HOME` anymore!! At least know that they are there and cannot be moved :smile:

**Comment by a2n-s** [comment]
I would like to work on a refactor of my _GitHub_ account this week-end, it's been on my mind for way too long...

But, once I'm done, count on me to open PRs and try to solve as best as I can the files listed above!

I thought about the following plan yesterday before going to bed:
  - adding a minimal support for all of the files at once, just to have them checked when running `xdg-ninja`
  - try to solve the hidden files that still hang around in my dotfiles repo (that's just to have an arbitrary starting point :wink:)
  - then address the others when possible

What do you think about that? :yum: 

Also, before beginning anything... What is the difference between _"Currently unsupported"_ and _"No help available"_ in the `.json` files? :thinking:

**Comment by wael444** [comment]
here's my effortless info that i managed to find
| file/directory | status | info |
| - | - | - |
| `.arduino-create` |  no information found  |
| `.eendroroy-coloschemes` |  no information found |
| `.links` |  no information found |
| `.lyrics` |  no information found |
| `.mujoco` |  no information found |
| `.oh-my-bash` |  no information found |
| `.oh-my-xonsh` |  no information found |
| `.quickemu` |  no information found |
| `.SpaceVim` |  no information found |
| `.SpaceVim.d` |  no information found |
| `.telegram-cli` |  no information found |
| `.trash` |  no information found |
| `.vim_back` |  no information found |
| `.info` |  no information found |
| `.boto` |  no information found |
| `.dmrc` |  no information found |
| `.luahistory` |  no information found |
| `.net.log` |  no information found |
| `.notion-enhancer` |  no information found |
| `.nwinkler_random_colors` |  no information found |
| `.osh-update` |  no information found |
| `.pdbhistory` |  no information found |
| `.sc_history` |  no information found |
| `.sdirs` |  no information found |
| `.xonshrc` |  no information found |
| `.xscreensaver` |  no information found |
| `.arduino15` |  won't fix |  https://github.com/arduino/Arduino/issues/3915 |
| `.kube` |  won't fix |  https://github.com/kubernetes/kubernetes/issues/56402 |
| `.pytest_cache` |  won't fix |  https://github.com/pytest-dev/pytest/issues/1089 |
| `.zotero` |  won't fix |  https://github.com/zotero/zotero/issues/1203 |
| `.bashrc` |  wont fix |  https://savannah.gnu.org/support/?108134 |
| `.bash_aliases` |  won't fix |  https://savannah.gnu.org/support/?108134 |
| `.bash_profile` |  won't fix |  https://savannah.gnu.org/support/?108134 |
| `.bash_login` |  won't fix |  https://savannah.gnu.org/support/?108134 |
| `.bash_logout` |  won't fix |  https://savannah.gnu.org/support/?108134 |
| `.ctags` |  wont fix |  https://github.com/universal-ctags/ctags/issues/89 |
| `.matho_history` |  won't fix |  `History can be moved by using rlwrap mathomatic -r with the RLWRAP_HOME environment set appropriately.` |
| `.profile` |  won't fix |
| `.pulse-cookie` |  won't fix |   |
| `.dwarffortess` |  unnoticed |  https://www.bay12games.com/dwarves/mantisbt/view.php?id=11800 |
| `.keras` |  unnoticed |  https://github.com/tensorflow/tensorflow/issues/38831 |
| `.gsutil` |  unnoticed |  https://github.com/GoogleCloudPlatform/gsutil/issues/991 |
| `.screenlayout` |  unnoticed |  https://gitlab.com/arandr/arandr/-/issues/45 |
| `.slime` |  unnoticed |  https://github.com/slime/slime/issues/610 |
| `.themes` |  supported |  `$XDG_DATA_HOME/themes` |
| `.trash` |  supported |  `$XDG_DATA_HOME/trash` |
| `.virtualbox` |  supported |
| `.gnuplot_history` |  supported |
| `.pulse-cookie` |  supported |
| `.rtorrent` |  supported |
| `.thumbnails` |  needs more information |  https://bugzilla.gnome.org/show_bug.cgi?id=166643 |
| `.vim` |  needs more information | `XDG_CONFIG_HOME/vim/vimrc` https://wiki.archlinux.org/title/XDG_Base_Directory#Supported |
| `.vimrc` |  needs more information |  https://wiki.archlinux.org/title/XDG_Base_Directory#Supported |
| `.viminfo` |  needs more information |  https://wiki.archlinux.org/title/XDG_Base_Directory#Supported |
| `.emacs.d` |  optional |  `XDG_CONFIG_HOME/emacs/init.el` |
| `.oh-my-zsh` |  optional |  `ZSH="~/.config/zsh/oh-my-zsh" sh installer.sh` |
| `.xmonad` |  optional |  `All of these must exist, otherwise it gives up and falls back to ~/.xmonad/ for each: XDG_CACHE_HOME/xmonad, XDG_CONFIG_HOME/xmonad, XDG_DATA_HOME/xmonad |
| `.yarnrc` |  optional |  `alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'` |
| `.zshrc` |  optional |  `$ZDOTDIR via ~/.zshenv` |
| `.zcompdump` |  optional |  `$ZDOTDIR via ~/.zshenv` |
| `.zsh_history` |  optional |  `$ZDOTDIR via ~/.zshenv` |
| `.ipython` |  optional |  `The default dotfile path is still $HOME but xdg directories (or ~/.config/ipython if XDG_* vars are unset) are supported and work correctly.` |
| `.moc` |  optional |  ` mocp -M "$XDG_CONFIG_HOME"/moc` `mocp -O MOCDir="$XDG_CONFIG_HOME"/moc` |
| `.surf` |  optional |  see `config.def.h` |

**Comment by wael444** [comment]
should i open a PR for the information i managed to gather?

**Comment by b3nj5m1n** [comment]
Thanks a lot @wael444, this is a great start.

> should i open a PR for the information i managed to gather?

Yes, let's start with the ones that are "won't fix" and don't have any relevant issues attached.

---

@a2n-s 

> I thought about the following plan yesterday before going to bed:
>>    adding a minimal support for all of the files at once, just to have them checked when running xdg-ninja
>>    try to solve the hidden files that still hang around in my dotfiles repo (that's just to have an arbitrary starting point wink)
>>    then address the others when possible
> What do you think about that?

I'm not sure what you mean by minimal support, but this sounds like a good plan to me. If we manage to add support for some of these before you get to it, I'll try to create and maintain a checklist in a comment here somewhere, so it's clear which ones have been addressed and which ones haven't.

> Also, before beginning anything... What is the difference between "Currently unsupported" and "No help available" in the .json files?

No help available is automatically inserted into the output when the "help" section is left completely blank. This is mostly for stuff that probably won't get xdg support, and where the either isn't a relevant issue to link to, or I was too lazy to dig it up. The goal is to reduce the number of files producing this.

Currently unsupported means it's not supported (you can also use this if there are no official plans to add support, i.e. it's been marked as won't fix), but these generally link to a relevant issue.

You shouldn't worry about this too much, as the helper program will generate a template for you based on whether the file can be moved or not.

**Comment by a2n-s** [comment]
> No help available is automatically inserted into the output when the "help" section is left completely blank. This is mostly for stuff that probably won't get xdg support, and where the either isn't a relevant issue to link to, or I was too lazy to dig it up. The goal is to reduce the number of files producing this.
> Currently unsupported means it's not supported (you can also use this if there are no official plans to add support, i.e. it's been marked as won't fix), but these generally link to a relevant issue.
> You shouldn't worry about this too much, as the helper program will generate a template for you based on whether the file can be moved or not.
>
ok I understand :ok_hand:

> I'm not sure what you mean by minimal support, but this sounds like a good plan to me. If we manage to add support for some of these before you get to it, I'll try to create and maintain a checklist in a comment here somewhere, so it's clear which ones have been addressed and which ones haven't.
>
I mean simply adding a blank file, or with "Currently unsupported" at least, to have the program in the database of `xdg-ninja`

I was willing to start working on that but do not want to produce duplicate work. Let's wait for @wael444 to respond to you and see if a PR is opened, no need to open twice the same PR :wink:

**Comment by wael444** [comment]
> I was willing to start working on that but do not want to produce duplicate work. Let's wait for @wael444 to respond to you and see if a PR is opened, no need to open twice the same PR wink

what do you exactly want me to do? just add the programs into `programs/` and open a PR?

**Comment by b3nj5m1n** [comment]
Add then using `cabal run xdgnj add`, that will add them to programs/, then open a PR.

**Comment by b3nj5m1n** [comment]
Just to clarify @wael444, since you said in https://github.com/b3nj5m1n/xdg-ninja/pull/79#issuecomment-1146837135 that you "have no idea how to use `cabal`", are you still planning to work on this?

**Comment by wael444** [comment]
> Just to clarify @wael444, since you said in [#79 (comment)](https://github.com/b3nj5m1n/xdg-ninja/pull/79#issuecomment-1146837135) that you "have no idea how to use `cabal`", are you still planning to work on this?

Sorry, I am unable work on it.

**Comment by a2n-s** [comment]
@b3nj5m1n, I will try to solve that issue as best as I can :wink:

Stay tuned :yum:

**Comment by a2n-s** [comment]
Sadly, I've not been able to compile the `haskell` code using `cabal run xdgnj add`...
i've tried `cabal update`, `cabal install --dependencies-only --ghc-option=-dynamic`, but none of them worked :thinking: 

I will fall back onto my editor of choice, that's not a big deal for the work to be done, just a bit sad not being successfull with a new tool :+1:

**Comment by b3nj5m1n** [comment]
Are you on arch linux? There's some additional configuration you need to do, namely adding the following to your cabal config:
```
library-vanilla: False
shared: True
executable-dynamic: True
program-default-options
  ghc-options: -dynamic
```
See also the [arch wiki page](https://wiki.archlinux.org/title/Haskell#Configuring_Cabal_for_dynamic_linking).

If it still doesn't work, you can also just write out the information and give it to me in a text file or something like that, then I'll add the properly formatted configs. Sorry about the inconvenience.

**Comment by b3nj5m1n** [comment]
I'll try to write a Dockerfile to make this easier.

**Comment by a2n-s** [comment]
> Are you on arch linux? There's some additional configuration you need to do, namely adding the following to your cabal config:
> 
yes I am :ok_hand: 

> ```
> library-vanilla: False
> shared: True
> executable-dynamic: True
> program-default-options
>   ghc-options: -dynamic
> ```
> 
> See also the [arch wiki page](https://wiki.archlinux.org/title/Haskell#Configuring_Cabal_for_dynamic_linking).
> 
that is super strange, it did not work...
i ran `cabal run xdgnj prev programs/git.json`... which worked
and now `cabal run xdgnj add` appears to be working :open_mouth: 

> If it still doesn't work, you can also just write out the information and give it to me in a text file or something like that, then I'll add the properly formatted configs. Sorry about the inconvenience.

that is not your fault at all :yum:

**Comment by a2n-s** [comment]
> I'll try to write a Dockerfile to make this easier.

that would be amazing :star_struck:

**Comment by a2n-s** [comment]
Below is a todo list of all the programs from the beginning of that issue:
- [x] .arduino-create/
- [x] .arduino15/
- [ ] .dwarffortress/
- [x] .eendroroy-coloschemes/
- [ ] .emacs.d/
- [ ] .gsutil/
- [ ] .ipython/
- [ ] .keras/
- [ ] .kube/
- [x] .links/
- [ ] .lyrics/
- [x] .moc/
- [x] .mujoco/
- [x] .oh-my-bash/
- [ ] .oh-my-xonsh/
- [ ] .pytest_cache/
- [ ] .quickemu/
- [ ] .screenlayout/
- [ ] .slime/
- [ ] .SpaceVim/
- [ ] .SpaceVim.d/
- [ ] .surf/
- [ ] .telegram-cli/
- [ ] .themes/
- [ ] .thumbnails/
- [ ] .trash/
- [ ] .vim/ -> ~/.SpaceVim/
- [ ] .vim_back/
- [ ] .virtualbox/
- [ ] .when/
- [ ] .xmonad/
- [ ] .zotero/
- [x] .bash_aliases
- [x] .bash_logout
- [x] .bash_profile
- [x] .bashrc
- [x] .bashrc.backup
- [ ] .boto
- [ ] .ctags
- [ ] .dmrc
- [ ] .gcalcli_cache
- [ ] .gcalcli_oauth
- [ ] .gnuplot_history
- [ ] .grip-oggenc
- [ ] .luahistory
- [ ] .matho_history
- [ ] .net.log
- [ ] .notion-enhancer
- [ ] .nwinkler_random_colors
- [ ] .osh-update
- [ ] .pdbhistory
- [ ] .profile
- [ ] .pulse-cookie
- [ ] .python_history-83827.tmp
- [ ] .rtorrent.rc
- [ ] .sc_history
- [ ] .sdirs
- [ ] .viminfo
- [ ] .vimrc_back
- [ ] .xonshrc
- [ ] .xscreensaver
- [ ] .yarnrc
- [ ] .zcompdump*
- [ ] .zsh_history

I push the first ones so that you can tell me if that's ok to you @b3nj5m1n :wink:

**Comment by b3nj5m1n** [comment]
> I'll try to write a Dockerfile to make this easier.

I added a dockerfile on a new branch, it builds a statically linked executable from the project, so it should run anywhere without any dependencies needed (?)

You can find the dockerfile [here](https://github.com/b3nj5m1n/xdg-ninja/blob/c94626c22d8460f71ee657ec629dc584cf4ef9e5/build/Dockerfile) and a prebuilt binary [here](https://github.com/b3nj5m1n/xdg-ninja/releases/tag/v0.2.0.0).

I'll give it a try later in a vm to see if it really works properly as a standalone binary, if it does, it should make using the helper program a lot easier.

**Comment by a2n-s** [comment]
And there we have it! The full list implemented in `./programs`.

Some of them are really unclear about what program that is and how to fix it, but this is the best so far, and people can still open issues to fix any problem :yum:

**Comment by a2n-s** [comment]
> > I'll try to write a Dockerfile to make this easier.
> 
> I added a dockerfile on a new branch, it builds a statically linked executable from the project, so it should run anywhere without any dependencies needed (?)
> 
> You can find the dockerfile [here](https://github.com/b3nj5m1n/xdg-ninja/blob/c94626c22d8460f71ee657ec629dc584cf4ef9e5/build/Dockerfile) and a prebuilt binary [here](https://github.com/b3nj5m1n/xdg-ninja/releases/tag/v0.2.0.0).
> 
> I'll give it a try later in a vm to see if it really works properly as a standalone binary, if it does, it should make using the helper program a lot easier.

really great news for future contributions :star_struck:

**Comment by a2n-s** [comment]
As this is fully merged, I close the issue :wink:
