### ISSUE TITLE
Provide docker image and binary to help contributions.

### ISSUE THREAD

**Issue by a2n-s** [b3nj5m1n/xdg-ninja#83]
This is simply to move the discussion from #80 to a separate issue, as #80 is almost closed with #81 being already merged and #82 being opened :wink:

**Comment by o0MURDOCK0o** [comment]
Just tested it and it works.

Tested it on:

- Arch with Haskell
- Arch without anything
- Ubuntu WSL on Win 10

**Comment by Willenbrink** [comment]
Just tested it too. Running the program works fine but in the end it throws an error related to the editor:
`xdgnj: EDITOR: getEnv: does not exist (no environment variable)`
Perhaps you could prompt for an editor instead of failing?

Besides that everything works. Looks good!

**Comment by a2n-s** [comment]
> Is it failing to run, or is it crashing with some kind of error message?
> 
oh no it is doing nothing at all, no errors, no message at whatsoever

**Comment by b3nj5m1n** [comment]
> > Is it failing to run, or is it crashing with some kind of error message?
> > 
> oh no it is doing nothing at all, no errors, no message at whatsoever
> 
> I wish I had something to show you :laughing: 

Wow that's weird, is it just a vanilla arch install (base, linux, linux-firmware packages)?

I'll try to reproduce it.

**Comment by a2n-s** [comment]
> Wow that's weird, is it just a vanilla arch install (base, linux, linux-firmware packages)?
> 
it should be :thinking: 
i always keep a vanilla arch installation inside `virtualbox` for that kind of purpose!
there should not be that much things in it, maybe `git` and `vim` and obviously `base-devel`, `linux` and `linux-firmware`

> I'll try to reproduce it.
>
tell me it there is anything to try out, now that `archinstall` is up and running, that is much easier to try things in a minute :muscle:

**Comment by b3nj5m1n** [comment]
Not everybody has responded yet, but since there haven't been any problems so far, I think it's safe to merge this.
