### ISSUE TITLE
xonsh can be moved!

### ISSUE THREAD

**Issue by a2n-s** [b3nj5m1n/xdg-ninja#84]
After some investigation, it appears that `.xonshrc` can be moved to `$XDG_CONFIG_HOME/xonsh/xonshrc` and `xonsh` can then be aliased to `xonsh --rc "$XDG_CONFIG_HOME/xonsh/xonshrc"`! :yum:

**Comment by b3nj5m1n** [comment]
> And I've got a branch with the change if you want me to open a PR

That would be great!

**Comment by a2n-s** [comment]
I'll do that soon :yum:
